name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: reporter-version
    attributes:
      label: `cypress-mochawesome-reporter` version
      placeholder: 2.2.0
    validations:
      required: true
  - type: input
    id: cypress-version
    attributes:
      label: `cypress` version
      placeholder: 7.6.0
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: `node` version
      placeholder: 14.17.1
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: cypress-config
    attributes:
      label: Config file
      description: Please add your `cypress.json` and `reporter-config.json` if used
      render: json
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output
  - type: textarea
    id: additional-info
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
